# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Payment Type

# Model Form Field configuration
form: @/plugins/responsiv/pay/models/type/fields.yaml

# Model Class name
modelClass: Responsiv\Pay\Models\Type

# Default redirect location
defaultRedirect: responsiv/pay/types

# Create page
create:
    title: Create Payment Type
    redirect: responsiv/pay/types/update/:id
    redirectClose: responsiv/pay/types

# Update page
update:
    title: Edit Payment Type
    redirect: responsiv/pay/types
    redirectClose: responsiv/pay/types

# Preview page
preview:
    title: Preview Payment Type