# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Invoice Template

# Model Form Field configuration
form: @/plugins/responsiv/pay/models/invoicetemplate/fields.yaml

# Model Class name
modelClass: Responsiv\Pay\Models\InvoiceTemplate

# Default redirect location
defaultRedirect: responsiv/pay/invoicetemplates

# Update page
update:
    title: Edit InvoicesTemplates
    redirect: responsiv/pay/invoicetemplates
    redirectClose: responsiv/pay/invoicetemplates
